### ISSUE TITLE
Open Source Code for MultiGPrompt

### ISSUE THREAD

**Issue by Starlien95** [WxxShirley/Awesome-Graph-Prompt#6]
Thanks for your awesome work! I'd like to kindly remind that the open source code for *MultiGPrompt for Multi-Task Pre-Training and Prompting on Graphs* is available at [https://github.com/Nashchou/MultiGPrompt](https://github.com/Nashchou/MultiGPrompt).

**Comment by WxxShirley** [comment]
Thank you very much for the reminder. 
I have just added MultiGPrompt's code, so I'd like to close this issue : )
