### ISSUE TITLE
Graph Domain Adaptation with Prompting Paper

### ISSUE THREAD

**Issue by Starlien95** [WxxShirley/Awesome-Graph-Prompt#7]
Thanks for your awesome work! I'd like to kindly introduce a preprint paper **[Text-Free Multi-domain Graph Pre-training: Toward Graph Foundation Models](https://arxiv.org/abs/2405.13934)**, which proposes a multi-domain pre-training and downstream adaptation strategy.

**Comment by WxxShirley** [comment]
Paper added. Thank you for your suggestion!
